import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import { NextAuthProvider } from "~/app/_components/NextAuthProvider";
import { LayoutHeader } from "~/app/_components/LayoutHeader";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {/*client component でも server component でも session が使えるようにする
         * ベストプラクティスがあるかもしれないが、とりあえずこのようにしている*/}
        <NextAuthProvider session={session}>
          <TRPCReactProvider>
            <LayoutHeader />
            <main className="min-h-screen">{children}</main>
          </TRPCReactProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
